# Generated by Django 4.0.1 on 2022-01-27 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summoner_name', models.CharField(max_length=32)),
                ('rateing', models.IntegerField(default=2, max_length=5)),
                ('comment_text', models.CharField(max_length=144)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summoner_1', models.CharField(max_length=32)),
                ('summoner_2', models.CharField(max_length=32)),
                ('summoner_3', models.CharField(max_length=32)),
                ('summoner_4', models.CharField(max_length=32)),
                ('summoner_5', models.CharField(max_length=32)),
                ('summoner_6', models.CharField(max_length=32)),
                ('summoner_7', models.CharField(max_length=32)),
                ('summoner_8', models.CharField(max_length=32)),
                ('summoner_9', models.CharField(max_length=32)),
                ('searched_summoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.summoner')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
            ],
        ),
    ]
