# Generated by Django 4.0.1 on 2022-01-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='rateing',
            field=models.IntegerField(default=2),
        ),
    ]
