# Generated by Django 4.0.1 on 2022-01-28 01:55

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_cattoy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('summoner_name', models.CharField(max_length=36)),
                ('summoner_lvl', models.IntegerField()),
                ('solo_rank', models.CharField(max_length=15)),
                ('flex_rank', models.CharField(max_length=15)),
                ('win_rate', models.IntegerField()),
                ('riot_id', models.CharField(max_length=63)),
                ('puuid', models.CharField(max_length=78)),
                ('account_id', models.CharField(max_length=56)),
                ('profile_icon_id', models.IntegerField()),
                ('profile_icon', models.ImageField(upload_to='')),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('items', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), size=7)),
                ('game_lvl', models.IntegerField()),
                ('creep_score', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='cat',
            name='cattoys',
            field=models.ManyToManyField(to='main_app.CatToy'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cattoy',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('solo_duo_rank', models.CharField(max_length=32)),
                ('rank_icon', models.ImageField(upload_to='')),
                ('flex_rank', models.IntegerField()),
                ('win_count', models.IntegerField()),
                ('loss_count', models.IntegerField()),
                ('lp', models.IntegerField()),
                ('summoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.summoner')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('game_type', models.CharField(max_length=32)),
                ('win_loss', models.BooleanField()),
                ('game_length', models.DurationField()),
                ('blue_dragons_taken', models.IntegerField()),
                ('blue_barons_taken', models.IntegerField()),
                ('blue_towers_taken', models.IntegerField()),
                ('blue_gold_total', models.IntegerField()),
                ('red_dragons_taken', models.IntegerField()),
                ('red_barons_taken', models.IntegerField()),
                ('red_towers_taken', models.IntegerField()),
                ('red_gold_total', models.IntegerField()),
                ('summoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.summoner')),
            ],
        ),
    ]
